name: Java CI with Maven + MySQL Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: "03@March$2025"
          MYSQL_DATABASE: connection
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -p'03@March$2025'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..20}; do
            if mysql -h 127.0.0.1 -P 3306 -uroot -p'03@March$2025' -e "SELECT 1" &> /dev/null; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting..."
            sleep 5
          done

      - name: Run Maven Tests
        run: mvn clean install -Dspring.profiles.active=test
